---
name: Connor
surname: Smith
position: "Informatics Research Associate"
address: "DMICE, Oregon Health & Science University"
phone: +1 503-347-0726
email: "smitco@ohsu.edu"
twitter: ConnorJPSmith
github: ConnorJPSmith
linkedin: ConnorJPSmith
aboutme: SQL, R, Data Visualization
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::moderncv:
    theme: classic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(rorcid)
library(lubridate)
library(tools)
```

```{r prep_data, include=FALSE, warning=FALSE}
# jobs
jobs <- read_csv(file = '../data/jobs.csv') %>%
  mutate(start = mdy(start),
         end = mdy(end),
         period = case_when(is.na(end) ~ paste0(year(start), '-Present'),
                            year(start) == year(end) ~ as.character(year(start)),
                            TRUE ~ paste0(year(start),'-',year(end)))) %>%
  arrange(desc(start)) #arrange(!is.na(end),desc(start)) #to have current jobs shown first
jobs_desc <- jobs %>% 
  inner_join(y = read_csv(file = '../data/jobs_desc.csv'),
             by = 'jobId')

# presentations
presentations <- read_csv(file = '../data/presentations.csv') %>%
  mutate(date = mdy(date))

# professional development
profDevel <- read_csv(file = '../data/professionalDevelopment.csv') %>%
  mutate(date = mdy(date))

# awards/honors
awards <- read_csv(file = '../data/awards_grants.csv') %>%
  mutate(date = mdy(date))
```


# Education

```{r education}
tribble(
  ~Degree, ~Dates, ~School, ~Location,
  'Masters of Science in Biomedical Informatics', '2016-2019', 'Oregon Health & Science University', 'Portland, OR',
  'Bachelors of Science in Biology', '2010-2014', 'Oregon State University', 'Corvallis, OR') %>% 
  detailed_entries(
    what = Degree,
    when = Dates, 
    with = School,
    where = Location
  )
```

# Work Experience  
```{r jobs}
jobs_desc %>%
  filter(type != 'military') %>%
  detailed_entries(what = position,
                   when = period,
                   with = employer,
                   where = paste0(city, ', ', state),
                   why = accomplishment)

```  

## Military Experience  
```{r military}
jobs_desc %>%
  filter(type == 'military') %>%
  detailed_entries(what = position,
                   when = period,
                   with = employer,
                   where = paste0(city, ', ', state),
                   why = accomplishment)

```

# Awards and Honors  
```{r awards}
awards %>%
  brief_entries(what = award,
                when = paste0(month(date, label = TRUE), ' ', year(date)),
                with = from)

```

# Publications

```{r pubs}
scholar::get_publications("H45dNhoAAAAJ") %>% 
  #filter(cites > 30) %>% 
  distinct(title, .keep_all = TRUE) %>%
  transmute(bibtype = "Article", author = as.character(author),
            title = as.character(title),
            journaltitle = as.character(journal), year, key = row_number()) %>% 
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib("smith.bib")

bibliography_entries("smith.bib")
```  

# Presentations  

## Talks  
```{r presentations_talks}
presentations %>%
  filter(type == 'talk') %>% 
  arrange(desc(date)) %>% 
  detailed_entries(what = title,
                   when = paste0(month(date, label = TRUE), ' ', year(date)),
                   with = event,
                   where = paste0(city, ', ', state))
```

## Workshops  
```{r presentations_workshops}
presentations %>%
  filter(type == 'workshop') %>% 
  arrange(desc(date)) %>% 
  detailed_entries(what = title,
                   when = paste0(month(date, label = TRUE), ' ', year(date)),
                   with = event,
                   where = paste0(city, ', ', state))
```  

## Competitions  
```{r presentations_comp}
presentations %>%
  filter(type == 'design challenge') %>% 
  arrange(desc(date)) %>% 
  detailed_entries(what = title,
                   when = paste0(month(date, label = TRUE), ' ', year(date)),
                   with = event,
                   where = paste0(city, ', ', state),
                   why = award)
```

# Service  

**Manuscript Reviews**  

- Applied Clinical Informatics (2)  

# Professional Development  
```{r profDevel}
profDevel %>% 
  arrange(desc(date)) %>% 
  detailed_entries(what = title,
                   when = date,
                   with = paste0(tools::toTitleCase(type), ' hosted by ',sponsor),
                   where = paste0(city, ', ', state))
```
